services:
  spring-app:
    image: spring:v1 
    ports:
      - "8085:8080"  
    depends_on:
      - mongodb
    networks:
      - mynetwork

  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_DATABASE: mydb
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_USERNAME: chedi
      MONGO_INITDB_PASSWORD: chedi

    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - mynetwork

volumes:
  mongo_data:

networks:
  mynetwork: